#pragma once

// EVENTS

// DOCKED 10
#define FSMEVENT_DOCKED__TO__DOCKED_MENU 10
#define FSMEVENT_DOCKED__TO__ERROR 19

// DOCKED MENU 20
#define FSMEVENT_DOCKED_MENU__TO__DOCKED 20
#define FSMEVENT_DOCKED_MENU__TO__EXIT_GARAGE 21
#define FSMEVENT_DOCKED_MENU__TO__TEST_MENU 22
#define FSMEVENT_DOCKED_MENU__TO__ERROR 29

// EXIT GARAGE 30
#define FSMEVENT_EXIT_GARAGE__TO__MOWING 30
#define FSMEVENT_EXIT_GARAGE__TO__PARKED 31
#define FSMEVENT_EXIT_GARAGE__TO__RANDOM_ROTATE 32
#define FSMEVENT_EXIT_GARAGE__TO__FIND_WIRE_FORWARDS 33
#define FSMEVENT_EXIT_GARAGE__TO__ROTATE_TO_WIRE 34
#define FSMEVENT_EXIT_GARAGE__TO__FIND_WIRE_BACKWARDS 35
#define FSMEVENT_EXIT_GARAGE__TO__ERROR 39

// MOWING 40
#define FSMEVENT_MOWING__TO__FIND_WIRE_FORWARDS 40
#define FSMEVENT_MOWING__TO__PARKED 41
#define FSMEVENT_MOWING__TO__RANDOM_ROTATE 42
#define FSMEVENT_MOWING__TO__FIND_WIRE_BACKWARDS 43
#define FSMEVENT_MOWING__TO__ERROR 49

// FOLLOW WIRE 60
#define FSMEVENT_FOLLOW_WIRE__TO__DOCKED 60
#define FSMEVENT_FOLLOW_WIRE__TO__PARKED 61
#define FSMEVENT_FOLLOW_WIRE__TO__WIRE_TO_GARDEN 62
#define FSMEVENT_FOLLOW_WIRE__TO__ERROR 69

// PARKED 70
#define FSMEVENT_PARKED__TO__PARKED_MENU 70
#define FSMEVENT_PARKED__TO__ERROR 79

// PARKED MENU 80
#define FSMEVENT_PARKED_MENU__TO__PARKED 80
#define FSMEVENT_PARKED_MENU__TO__FOLLOW_WIRE 81
#define FSMEVENT_PARKED_MENU__TO__FIND_WIRE_FORWARDS 82
#define FSMEVENT_PARKED_MENU__TO__RANDOM_ROTATE 83
#define FSMEVENT_PARKED_MENU__TO__FIND_WIRE_BACKWARDS 84
#define FSMEVENT_PARKED_MENU__TO__ERROR 89

// RANDOM ROTATE 90
#define FSMEVENT_RANDOM_ROTATE__TO__MOWING 90
#define FSMEVENT_RANDOM_ROTATE__TO__PARKED 91
#define FSMEVENT_RANDOM_ROTATE__TO__ERROR 99

// WIRE TO GARDEN 100
#define FSMEVENT_WIRE_TO_GARDEN__TO__PARKED 100
#define FSMEVENT_WIRE_TO_GARDEN__TO__MOWING 101
#define FSMEVENT_WIRE_TO_GARDEN__TO__ERROR 109

// TEST MENU 110
#define FSMEVENT_TEST_MENU__TO__DOCKED_MENU 110
#define FSMEVENT_TEST_MENU__TO__ERROR 119

// ERROR 120
#define FSMEVENT_ERROR__TO__PARKED 120

// COMPASS 130
#define FSMEVENT_COMPASS_ROTATE__TO__PARKED 130
#define FSMEVENT_COMPASS_ROTATE__TO__ERROR 139

// ROTATE TO WIRE 140
#define FSMEVENT_ROTATE_TO_WIRE__TO__FIND_WIRE_FORWARDS 140
#define FSMEVENT_ROTATE_TO_WIRE__TO__PARKED 141
#define FSMEVENT_ROTATE_TO_WIRE__TO__FIND_WIRE_BACKWARDS 142
#define FSMEVENT_ROTATE_TO_WIRE__TO__ERROR 149

// FIND WIRE FORWARDS 200
#define FSMEVENT_FIND_WIRE_FORWARDS__TO__FOLLOW_WIRE 200
#define FSMEVENT_FIND_WIRE_FORWARDS__TO__PARKED 201
#define FSMEVENT_FIND_WIRE_FORWARDS__TO__FIND_WIRE_BACKWARDS 202
#define FSMEVENT_FIND_WIRE_FORWARDS__TO__ERROR 209

// FIND WIRE BACKWARDS 210
#define FSMEVENT_FIND_WIRE_BACKWARDS__TO__FOLLOW_WIRE 210
#define FSMEVENT_FIND_WIRE_BACKWARDS__TO__PARKED 211
#define FSMEVENT_FIND_WIRE_BACKWARDS__TO__FIND_WIRE_FORWARDS 212
#define FSMEVENT_FIND_WIRE_BACKWARDS__TO__ERROR 219
