#pragma once

// EXIT GARAGE 10
// EXIT GARAGE -> RANDOM ROTATE -> MOWING
#define FSMSEQUENCE_EXIT_GARAGE__RANDOM_ROTATE__MOWING 10
// EXIT GARAGE -> ROTATE TO WIRE -> FIND WIRE -> FOLLOW WIRE ZONE 1 -> WIRE TO GARDEN -> MOWING
#define FSMSEQUENCE_EXIT_GARAGE_MOW_FROM_ZONE_1 11
// EXIT GARAGE -> ROTATE TO WIRE -> FIND WIRE -> FOLLOW WIRE ZONE 2 -> WIRE TO GARDEN -> MOWING
#define FSMSEQUENCE_EXIT_GARAGE_MOW_FROM_ZONE_2 12
// PARKED -> FOLLOW WIRE
#define FSMSEQUENCE_FOLLOW_WIRE 13
