#pragma once

// EXIT GARAGE -> ROTATE TO WIRE -> FIND WIRE -> FOLLOW WIRE ZONE 1 -> WIRE TO GARDEN -> MOWING
#define FSMSEQUENCE_ZONE_1 11
// EXIT GARAGE -> ROTATE TO WIRE -> FIND WIRE -> FOLLOW WIRE ZONE 2 -> WIRE TO GARDEN -> MOWING
#define FSMSEQUENCE_ZONE_2 12
// PARKED -> FOLLOW WIRE
#define FSMSEQUENCE_FOLLOW_WIRE 13
// ALARM MOWING
#define FSMSEQUENCE_ALARM_1 14
#define FSMSEQUENCE_ALARM_2 15
#define FSMSEQUENCE_ALARM_3 16
// QUICK MOW
#define FSMSEQUENCE_QUICK_MOW 17
