#pragma once

// EXIT GARAGE -> ROTATE TO WIRE -> FIND WIRE -> FOLLOW WIRE ZONE 1 -> WIRE TO GARDEN -> MOWING
#define FSMSEQUENCE_ZONE_1 11
// EXIT GARAGE -> ROTATE TO WIRE -> FIND WIRE -> FOLLOW WIRE ZONE 2 -> WIRE TO GARDEN -> MOWING
#define FSMSEQUENCE_ZONE_2 12
// QUICK MOW
// EXIT GARAGE -> RANDOM ROTATE -> MOWING
#define FSMSEQUENCE_QUICK_MOW 13
// PARKED -> FOLLOW WIRE
#define FSMSEQUENCE_GO_TO_DOCK 14
