#pragma once

void Manouver_Mow_The_Grass();
void Manouver_Mow_The_Grass2();
void Manouver_Find_Wire_Track2();
void Manouver_Turn_Around();
void Manouver_Turn_Around_Sonar();
void Manouver_Manuel_Mode();
void Manouver_Start_Mower();
void Manouver_Mower_Exit_Dock();
void Manouver_Dock_The_Mower();
void Manouver_Park_The_Mower_Low_Batt();
void Manouver_Park_The_Mower();
void Manouver_Hibernate_Mower();
void Manouver_Go_To_Charging_Station();
void Manouver_Go_To_Charging_Station2();
void Manouver_Exit_To_Zone_X();
void Manouver_Outside_Wire_ReFind_Function();
void Manouver_SpinMowerToWire();
void Manouver_Exit_From_Docking_Station();